### ISSUE TITLE
Using TAU on Rhea

### ISSUE THREAD

**Issue by suchyta1** [wdmapp/wdmapp-config#51]
Has anyone else tried TAU on Rhea with `+papi`? I'm getting this in XGC when I do that:
```
Error: To use TAU's PAPI RAPL Perf interface please ensure that /proc/sys/kernel/perf_event_paranoid has a -1 in it.
```

I haven't seen that when I turn PAPI off. Do we want to turn it off in general? I haven't tried with `+papi` on Summit either, but it might work there.

**Comment by germasch** [comment]
I remember that @khuck had mentioned that he had had some issues with tau on rhea, but I don't know any of the details.

**Comment by khuck** [comment]
@suchyta1 @germasch Ah, yeah, that is so that the PAPI RAPL component can read power.  Does the spack installation of PAPI configure the RAPL component by default?  If you disable that, it should be fine.  Otherwise, you can tell TAU to ignore that component with a configuration file setting.

**Comment by khuck** [comment]
Actually...the PAPI spack package doesn't enable that component by default.  If that component isn't available, TAU should not try to use it.  I'll look into it.

**Comment by suchyta1** [comment]
PAPI was installed with the `-rapl` variant, but when I look at the build log there are some things with RAPL being build. And looking at the Spack package for PAPI, the `rapl` variant doesn't actually do anything.

**Comment by khuck** [comment]
I just checked the TAU code, and this error is coming from the PAPI initialization.  It doesn't take into consideration whether the user and/or PAPI wants RAPL or not, it just checks the paranoid bit.  I'll fix TAU.

**Comment by suchyta1** [comment]
Never mind on it not doing anything. It just was just implemented differently than my quick search picked up on. It's not adding rapl to `--with-components` so I think it's indeed trying not to use it.

**Comment by khuck** [comment]
@suchyta1 I just pushed a fix to master, and it's in the process of mirroring to GitHub.  Please try again in a few minutes and see if you get the same error.

**Comment by suchyta1** [comment]
@khuck Thanks. That fixed it.
